import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "../styles/globals.css"
import { firaCode, inter } from "@/styles/fonts";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg" />
      </head>
    <body className={`${inter.variable} ${firaCode.variable}`}>
      <AuthProvider>
        <Header />
        <div className="containerClient">
          {children}
        </div>
      </AuthProvider>
    </body>
    </html>
  );
}
